server:
  log_level: info
metrics:
  global:
    scrape_interval: 15s
    external_labels:
      project_id: test
      project_name: test
    remote_write:
      - url: https://example.com/write
        basic_auth:
          username: user
          password: pass
  wal_directory: /tmp/telescope
  configs:
    - name: test_polkadot_metrics
      host_filter: false
      scrape_configs:
        - job_name: test_polkadot_relaychain_job_0
          static_configs:
            - targets:
                - localhost:30333
        - job_name: test_polkadot_parachains_job_1
          static_configs:
            - targets:
                - localhost:9933
logs:
  configs:
    - name: telescope_logs
      clients:
        - url: https://loki.example.com/loki/api/v1/push
          basic_auth:
            username: user
            password: pass
          external_labels:
            project_id: test
            project_name: test
      positions:
        filename: /tmp/telescope_logs
      scrape_configs:
        - job_name: test_docker_logs
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - source_labels:
                - __meta_docker_container_name
              regex: /(.*)
              target_label: container
            - source_labels:
                - __meta_docker_container_log_stream
              target_label: logstream
            - source_labels:
                - __meta_docker_container_label_scrape_location
              target_label: job
            - source_labels:
                - __meta_docker_container_label_scrape_location
              target_label: scrape_location
            - source_labels:
                - __meta_docker_container_label_instance
              target_label: instance
            - source_labels:
                - __meta_docker_container_label_network
              target_label: network
            - source_labels:
                - __meta_docker_container_label_client_name
              target_label: client_name
            - source_labels:
                - __meta_docker_container_label_group
              target_label: group
            - source_labels:
                - __meta_docker_container_label_host_type
              target_label: host_type
            - source_labels:
                - __meta_docker_container_label_project_name
              target_label: project_name
            - source_labels:
                - __meta_docker_container_label_project_id
              target_label: project_id
integrations:
  agent:
    autoscrape:
      enable: true
      metrics_instance: test_polkadot_metrics
  node_exporter:
    autoscrape:
      enable: true
      metrics_instance: test_polkadot_metrics
