{
 "title": "Ethereum Geth Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "project_id", "query": { "query": "label_values(project_id)" } },
   {
    "name": "project_name",
    "query": {
     "query": "label_values({project_id=\"$project_id\"},project_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\", project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clean cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_write{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}