{
 "title": "Lighthouse Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "project_id", "label": "project_id", "query": { "query": "label_values(project_id)" } },
   {
    "name": "project_name",
    "label": "Nodes",
    "query": {
     "query": "label_values({project_id=\"$project_id\"},project_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. Validator Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_total_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Withdrawable Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_withdrawn_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Current Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(slotclock_present_slot{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lighthouse_info{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Avg. Slashed Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_slashed_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Avg. Current Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(slotclock_present_epoch{project_id=\"$project_id\", project_name=\"$project_name\"})"
    }
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_loadavg_1{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_virt_mem_free_bytes{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Lighthouse Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 13 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slots since Best Block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slotclock_present_slot{project_id=\"$project_id\", project_name=\"$project_name\"} - beacon_head_state_slot{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Justification (Min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{project_id=\"$project_id\", project_name=\"$project_name\"} - beacon_head_state_current_justified_epoch{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{project_id=\"$project_id\", project_name=\"$project_name\"} - beacon_head_state_finalized_epoch{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Target Attesting Balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attester{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Head Attesting Balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_head_attester{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Attesters",
   "type": "timeseries",
   "description": "The number of attesters for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_attesters{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Aggregators",
   "type": "timeseries",
   "description": "The number of aggregators for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_aggregators{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Validator Balances",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total{project_id=\"$project_id\", project_name=\"$project_name\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_head_state_active_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_head_state_total_validators_total{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Finalized Root (hash shown as int)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "beacon_head_state_finalized_root{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Total Fork Choice Re-Orgs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_fork_choice_reorg_total{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": { "content": "\n### Networking\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "libp2p Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "bargauge",
   "description": "Peers via client implementations",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libp2p_peers_per_client{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_requests{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "Discovery Requests Per Second"
    }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_sessions{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "discovery_queue_size{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "Queued Discoveries"
    }
   ]
  },
  {
   "title": "Total Libp2p Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(libp2p_bandwidth_bytes_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m]))",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(libp2p_bandwidth_bytes_total{direction=\"Inbound\", project_id=\"$project_id\", project_name=\"$project_name\"}[1m]))",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(libp2p_bandwidth_bytes_total{direction=\"Outbound\", project_id=\"$project_id\", project_name=\"$project_name\"}[1m]))",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
   "options": { "content": "### Gossipsub Metrics" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mesh peers per topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_main_topic{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Average Peer Score per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_topic{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Mesh peers per subnet",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_subnet_topic{project_id=\"$project_id\", project_name=\"$project_name\"}",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 },
   "options": { "content": "\n### Logging\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Crit Logs Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "crit_total{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(error_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(warn_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "title": "Info Logs per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(info_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 83 },
   "options": {
    "content": "\n### Core BeaconChain Functions\n\nTiming of core `BeaconChain` functions and syncing.\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Processing Times (24s moving avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum{project_id=\"$project_id\", project_name=\"$project_name\"}[30s])\n/\nrate(beacon_block_processing_seconds_count{project_id=\"$project_id\", project_name=\"$project_name\"}[30s])"
    }
   ]
  },
  {
   "title": "Find & Update Head Routine (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])\n/\nrate(beacon_fork_choice_seconds_count{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "title": "Syncing Slots per Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sync_slots_per_second{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "Block Tree Hash Times (5m avg)",
   "type": "timeseries",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum{project_id=\"$project_id\", project_name=\"$project_name\"}[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count{project_id=\"$project_id\", project_name=\"$project_name\"}[5m])"
    }
   ]
  },
  {
   "title": "State Tree Hash Times (5m avg)",
   "type": "timeseries",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum{project_id=\"$project_id\", project_name=\"$project_name\"}[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count{project_id=\"$project_id\", project_name=\"$project_name\"}[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 95 },
   "options": {
    "content": "\n### Database\n\nStats about the on-disk database (LevelDB)\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "On-Disk Database Size (Hot DB Only)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "store_disk_db_size{project_id=\"$project_id\", project_name=\"$project_name\"}"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  },
  {
   "title": "Persist Beacon Chain Times (1m avg)",
   "type": "timeseries",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_persist_chain_sum{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])\n/\nrate(beacon_persist_chain_count{project_id=\"$project_id\", project_name=\"$project_name\"}[1m])"
    }
   ]
  }
 ]
}