{
 "title": "Hyperbridge Nodes Dashboards",
 "description": "Telescope | A Node Observability tool by @blockopsnetwork",
 "tags": [
  "parachain",
  "polkadot",
  "hyperbridge"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Projects",
    "query": {
     "query": "label_values({project_id=\"hyperbridge\"},project_id)"
    }
   },
   {
    "name": "project_name",
    "label": "Nodes",
    "query": {
     "query": "label_values({project_id=\"${PROJECT_ID}\"},project_name)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values({project_name=\"${PROJECT_NAME}\"},chain)"
    }
   },
   {
    "name": "instance",
    "label": "Chain Instance Host",
    "query": {
     "query": "label_values({project_name=\"${PROJECT_NAME}\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Server Job",
    "query": {
     "query": "label_values({project_name=\"hyperbridge-gargantua\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Server Host",
    "query": {
     "query": "label_values({project_name=\"hyperbridge-gargantua\"},instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "description": "Disk Space Used% Basic",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}) /  count(count(node_cpu_seconds_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}) by (cpu)) * 100"
    },
    {}
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}) /  count(count(node_cpu_seconds_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} * 100) / node_memory_MemTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"})",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\", mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\", mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} - node_boot_time_seconds{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"[[metric_namespace]]\",memtype=\"resident\"}",
     "legendFormat": "Polkadot"
    },
    {
     "expr": "node_memory_MemTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} - node_memory_MemFree_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} - (node_memory_Cached_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} + node_memory_Buffers_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} + node_memory_Buffers_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} - node_memory_SwapFree_bytes{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{project_id=\"${PROJECT_ID}\", project_name=\"${PROJECT_NAME}\"} [5m])",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  }
 ]
}