{
 "title": "$project_id Network Dashboard",
 "description": "Telescope | A Node Observability tool by @blockopsnetwork",
 "tags": [
  "parachain",
  "$project_id"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "project_id", "label": "Projects", "query": { "query": "label_values(project_id)" } },
   {
    "name": "project_name",
    "label": "Nodes",
    "query": {
     "query": "label_values({project_id=\"$project_id\"},project_name)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values({project_name=\"$project_name\"},chain)"
    }
   },
   {
    "name": "instance",
    "label": "Chain Instance Host",
    "query": {
     "query": "label_values({project_name=\"$project_id-gargantua\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Server Job",
    "query": {
     "query": "label_values({project_name=\"$project_id-gargantua\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Server Host",
    "query": {
     "query": "label_values({project_name=\"$project_id-gargantua\"},instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Network & Chain Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Height of the chain $project_id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Tasks rate", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 } },
  { "title": "Running Tasks", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Peers count"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_requested{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_number_leaves{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\", project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}[10m])*60",
     "legendFormat": "{{instance}}  Blocks / minute"
    }
   ]
  },
  {
   "title": "No of Open RPC connections $project_id",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_closed_total{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Closed connections"
    },
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_opened_total{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}",
     "legendFormat": "Open connections"
    },
    {
     "expr": "(substrate_sub_libp2p_distinct_peers_connections_opened_total{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"}) - (substrate_sub_libp2p_distinct_peers_connections_closed_total{project_id=\"$project_id\", project_name=\"$project_name\", chain=\"$chain\"})",
     "legendFormat": "Queued connections"
    }
   ]
  },
  {
   "title": "Chain Logs $project_name",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{host=\"$project_name\"} |= ``"
    },
    {
     "expr": "{source=\"stderr\", host=\"$project_id\"} |= ``",
     "legendFormat": "Error Logs"
    }
   ]
  }
 ]
}